
import { useState, useEffect } from "react";
import { supabase } from "./supabase";

const todayStr = () => new Date().toISOString().split("T")[0];

const formatDate = (d) => {
const dt = new Date(d + "T12:00:00");
return dt.toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" });
};

const EMPTY_LOG = {
date: todayStr(),
weight: "",
energy: "",
vitals: {
morning: { sys: "", dia: "", hr: "" },
afternoon: { sys: "", dia: "", hr: "" },
evening: { sys: "", dia: "", hr: "" },
},
workouts: {
home: { bike1: "", bike2: "", bike3: "" },
gym: { bike: "", rowing: "" },
machines: {
backExtension: { sets: "", reps: "", weight: "" },
abdominal: { sets: "", reps: "", weight: "" },
shoulderPress: { sets: "", reps: "", weight: "" },
chestPress: { sets: "", reps: "", weight: "" },
seatedRow: { sets: "", reps: "", weight: "" },
tricepExtension: { sets: "", reps: "", weight: "" },
glutExtension: { sets: "", reps: "", weight: "" },
},
},
meals: {
breakfast: "", snack1: "", lunch: "",
snack2: "", dinner: "", snack3: "",
},
notes: "",
};

const MACHINE_LABELS = {
backExtension: "Back Extension", abdominal: "Abdominal",
shoulderPress: "Shoulder Press", chestPress: "Chest Press",
seatedRow: "Seated Row", tricepExtension: "Tricep Extension",
glutExtension: "Glut Extension",
};

const MEAL_LABELS = {
breakfast: { label: "Breakfast", icon: "🌅" },
snack1: { label: "Snack · Breakfast → Lunch", icon: "🍎" },
lunch: { label: "Lunch", icon: "☀️" },
snack2: { label: "Snack · Lunch → Dinner", icon: "🥜" },
dinner: { label: "Dinner", icon: "🌙" },
snack3: { label: "Snack · After Dinner", icon: "🍵" },
};

const ENERGY_LABELS = ["", "💀 Rough", "😓 Low", "😐 Okay", "😊 Good", "🔥 Strong"];

const deepClone = (obj) => JSON.parse(JSON.stringify(obj));

const generateCoachSummary = (log) => {
const lines = [];
lines.push(`╔════════════════════════════════════════╗`);
lines.push(` 📋 DAILY LOG · ${formatDate(log.date)}`);
lines.push(`╚════════════════════════════════════════╝`);
lines.push(``);
if (log.weight) lines.push(`⚖️ Weight ········ ${log.weight} lbs`);
if (log.energy) lines.push(`⚡ Energy ········ ${ENERGY_LABELS[log.energy]} (${log.energy}/5)`);
const vKeys = [["morning","Morning"],["afternoon","Afternoon"],["evening","Evening"]];
const hasVitals = vKeys.some(([k]) => log.vitals[k].sys);
if (hasVitals) {
lines.push(``); lines.push(`🩺 VITALS`);
vKeys.forEach(([k, label]) => {
const v = log.vitals[k];
if (v.sys) lines.push(` ${label.padEnd(10)} ${v.sys}/${v.dia} mmHg${v.hr ? ` · HR ${v.hr} bpm` : ""}`);
});
}
const h = log.workouts.home;
const homeSets = [h.bike1&&`Set 1: ${h.bike1} mi`,h.bike2&&`Set 2: ${h.bike2} mi`,h.bike3&&`Set 3: ${h.bike3} mi`].filter(Boolean);
if (homeSets.length) { lines.push(``); lines.push(`🚴 HOME · Xterra Amati`); homeSets.forEach(s=>lines.push(` ${s}`)); }
const g = log.workouts.gym;
if (g.bike||g.rowing) {
lines.push(``); lines.push(`🏋️ GYM`);
if (g.bike) lines.push(` Stationary Bike ${g.bike} mi`);
if (g.rowing) lines.push(` Rowing Machine ${g.rowing} min`);
}
const machineLines = Object.entries(MACHINE_LABELS).map(([key,label]) => {
const m = log.workouts.machines[key];
if (!m.sets&&!m.reps&&!m.weight) return null;
return ` ${label.padEnd(18)} ${[m.sets&&`${m.sets} sets`,m.reps&&`${m.reps} reps`,m.weight&&`${m.weight} lbs`].filter(Boolean).join(" · ")}`;
}).filter(Boolean);
if (machineLines.length) { lines.push(``); lines.push(`💪 PRECOR MACHINES`); machineLines.forEach(l=>lines.push(l)); }
const mealLines = Object.entries(MEAL_LABELS).map(([key,{label,icon}]) => {
const val = log.meals[key];
if (!val.trim()) return null;
return ` ${icon} ${label}\n ${val}`;
}).filter(Boolean);
if (mealLines.length) { lines.push(``); lines.push(`🥗 MEALS`); mealLines.forEach(l=>lines.push(l)); }
if (log.notes.trim()) { lines.push(``); lines.push(`📝 NOTES`); lines.push(` ${log.notes}`); }
lines.push(``); lines.push(`────────────────────────────────────────`);
lines.push(`Generated by Tim's Wellness Log v3.0`);
return lines.join("\n");
};

const Field = ({ label, value, onChange, placeholder, unit }) => (
<div style={{ display:"flex", flexDirection:"column", gap:5, flex:"1 1 90px", minWidth:80 }}>
<label style={{ fontSize:10, letterSpacing:"0.13em", color:"#7a84a8", textTransform:"uppercase", fontFamily:"'Syne Mono', monospace" }}>
{label}{unit ? <span style={{ color:"#4a5270", marginLeft:4 }}>({unit})</span> : null}
</label>
<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder||"—"}
style={{ background:"#10131e", border:"1px solid #252c42", borderRadius:8, color:"#dde0f0", padding:"8px 11px", fontSize:13, fontFamily:"'Syne Mono', monospace", outline:"none", width:"100%", boxSizing:"border-box" }}
onFocus={e=>{ e.target.style.borderColor="#4f7fe8"; e.target.style.boxShadow="0 0 0 3px rgba(79,127,232,0.12)"; }}
onBlur={e=>{ e.target.style.borderColor="#252c42"; e.target.style.boxShadow="none"; }}
/>
</div>
);

const TextArea = ({ label, value, onChange, placeholder }) => (
<div style={{ display:"flex", flexDirection:"column", gap:5, width:"100%" }}>
<label style={{ fontSize:10, letterSpacing:"0.13em", color:"#7a84a8", textTransform:"uppercase", fontFamily:"'Syne Mono', monospace" }}>{label}</label>
<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder||"—"} rows={2}
style={{ background:"#10131e", border:"1px solid #252c42", borderRadius:8, color:"#dde0f0", padding:"8px 11px", fontSize:13, fontFamily:"'Syne Mono', monospace", outline:"none", width:"100%", boxSizing:"border-box", resize:"vertical" }}
onFocus={e=>{ e.target.style.borderColor="#4f7fe8"; e.target.style.boxShadow="0 0 0 3px rgba(79,127,232,0.12)"; }}
onBlur={e=>{ e.target.style.borderColor="#252c42"; e.target.style.boxShadow="none"; }}
/>
</div>
);

const Section = ({ title, icon, accent, children }) => (
<div style={{ marginBottom:24, borderRadius:16, overflow:"hidden", boxShadow:"0 4px 24px rgba(0,0,0,0.2)", background:"#141824", border:`1px solid ${accent}28` }}>
<div style={{ padding:"12px 20px", background:`linear-gradient(90deg, ${accent}14 0%, transparent 80%)`, borderBottom:`1px solid ${accent}25`, display:"flex", alignItems:"center", gap:10 }}>
<span style={{ fontSize:16 }}>{icon}</span>
<span style={{ fontFamily:"'Syne', sans-serif", fontSize:13, fontWeight:600, letterSpacing:"0.12em", color:accent, textTransform:"uppercase" }}>{title}</span>
</div>
<div style={{ padding:"18px 20px" }}>{children}</div>
</div>
);

const Divider = ({ label }) => (
<div style={{ display:"flex", alignItems:"center", gap:10, margin:"14px 0 12px" }}>
<div style={{ height:1, flex:1, background:"#1e2438" }} />
<span style={{ fontSize:9, color:"#4a5270", letterSpacing:"0.15em", textTransform:"uppercase", fontFamily:"'Syne Mono', monospace" }}>{label}</span>
<div style={{ height:1, flex:1, background:"#1e2438" }} />
</div>
);

const VitalsRow = ({ label, data, onChange }) => (
<div style={{ marginBottom:14 }}>
<div style={{ fontSize:10, letterSpacing:"0.1em", color:"#5d667f", marginBottom:8, fontFamily:"'Syne Mono', monospace", textTransform:"uppercase" }}>{label}</div>
<div style={{ display:"flex", gap:10, flexWrap:"wrap" }}>
<Field label="Systolic" unit="mmHg" value={data.sys} onChange={v=>onChange("sys",v)} placeholder="120" />
<Field label="Diastolic" unit="mmHg" value={data.dia} onChange={v=>onChange("dia",v)} placeholder="80" />
<Field label="Resting HR" unit="bpm" value={data.hr} onChange={v=>onChange("hr",v)} placeholder="65" />
</div>
</div>
);

const MachineRow = ({ label, data, onChange }) => (
<div style={{ display:"flex", alignItems:"flex-end", gap:10, padding:"10px 0", borderBottom:"1px solid #1a1f30", flexWrap:"wrap" }}>
<div style={{ minWidth:148, fontSize:12, color:"#b8bcda", fontFamily:"'Syne Mono', monospace", paddingBottom:4, flex:"0 0 148px" }}>{label}</div>
<Field label="Sets" value={data.sets} onChange={v=>onChange("sets",v)} placeholder="5" />
<Field label="Reps" value={data.reps} onChange={v=>onChange("reps",v)} placeholder="20" />
<Field label="Weight" unit="lbs" value={data.weight} onChange={v=>onChange("weight",v)} placeholder="—" />
</div>
);

const HistoryDetail = ({ entry, onBack, onEdit, onDelete }) => {
const vKeys = [["morning","Morning"],["afternoon","Afternoon"],["evening","Evening"]];
const hasVitals = vKeys.some(([k]) => entry.vitals[k].sys);
const h = entry.workouts.home;
const homeMiles = [h.bike1,h.bike2,h.bike3].filter(Boolean);
const hasMachines = Object.keys(MACHINE_LABELS).some(k => entry.workouts.machines[k].sets||entry.workouts.machines[k].reps||entry.workouts.machines[k].weight);
const hasMeals = Object.keys(MEAL_LABELS).some(k => entry.meals[k].trim());
return (
<div>
<button onClick={onBack} style={{ background:"none", border:"none", color:"#4f7fe8", cursor:"pointer", fontSize:12, fontFamily:"'Syne Mono', monospace", letterSpacing:"0.08em", padding:"0 0 20px 0" }}>‹ Back to History</button>
<div style={{ fontFamily:"'Syne', sans-serif", fontSize:18, fontWeight:700, color:"#dde0f0", marginBottom:4 }}>{formatDate(entry.date)}</div>
{entry.energy && <div style={{ fontSize:13, color:"#a67cfc", marginBottom:8, fontFamily:"'Syne Mono', monospace" }}>⚡ {ENERGY_LABELS[entry.energy]} ({entry.energy}/5)</div>}
{entry.weight && <div style={{ fontSize:28, fontFamily:"'Syne', sans-serif", fontWeight:700, color:"#4f7fe8", marginBottom:20 }}>{entry.weight} <span style={{ fontSize:12, color:"#4a5270", fontWeight:400 }}>lbs</span></div>}
{hasVitals && (
<Section title="Vitals" icon="🩺" accent="#e05c7a">
{vKeys.map(([k,label]) => entry.vitals[k].sys ? (
<div key={k} style={{ marginBottom:10 }}>
<div style={{ fontSize:10, color:"#5d667f", textTransform:"uppercase", letterSpacing:"0.1em", marginBottom:4, fontFamily:"'Syne Mono', monospace" }}>{label}</div>
<div style={{ fontSize:15, color:"#dde0f0", fontFamily:"'Syne Mono', monospace" }}>{entry.vitals[k].sys}/{entry.vitals[k].dia} mmHg{entry.vitals[k].hr && <span style={{ color:"#7a84a8", marginLeft:12 }}>· {entry.vitals[k].hr} bpm</span>}</div>
</div>
) : null)}
</Section>
)}
{(homeMiles.length>0||entry.workouts.gym.bike||entry.workouts.gym.rowing||hasMachines) && (
<Section title="Workouts" icon="💪" accent="#4f7fe8">
{homeMiles.length>0 && (<><Divider label="At Home — Xterra Amati" /><div style={{ display:"flex", gap:16, flexWrap:"wrap", marginBottom:6 }}>{[h.bike1,h.bike2,h.bike3].map((v,i)=>v?<div key={i} style={{ fontSize:13, color:"#dde0f0", fontFamily:"'Syne Mono', monospace" }}>Set {i+1}: <span style={{ color:"#4f7fe8" }}>{v} mi</span></div>:null)}</div></>)}
{(entry.workouts.gym.bike||entry.workouts.gym.rowing) && (<><Divider label="At the Gym" />{entry.workouts.gym.bike&&<div style={{ fontSize:13, color:"#dde0f0", fontFamily:"'Syne Mono', monospace", marginBottom:6 }}>Stationary Bike: <span style={{ color:"#4f7fe8" }}>{entry.workouts.gym.bike} mi</span></div>}{entry.workouts.gym.rowing&&<div style={{ fontSize:13, color:"#dde0f0", fontFamily:"'Syne Mono', monospace" }}>Rowing Machine: <span style={{ color:"#4f7fe8" }}>{entry.workouts.gym.rowing} min</span></div>}</>)}
{hasMachines && (<><Divider label="Precor Machines" />{Object.entries(MACHINE_LABELS).map(([key,label])=>{ const m=entry.workouts.machines[key]; if(!m.sets&&!m.reps&&!m.weight) return null; const parts=[m.sets&&`${m.sets} sets`,m.reps&&`${m.reps} reps`,m.weight&&`${m.weight} lbs`].filter(Boolean).join(" · "); return <div key={key} style={{ display:"flex", justifyContent:"space-between", padding:"8px 0", borderBottom:"1px solid #1a1f30", fontSize:12, fontFamily:"'Syne Mono', monospace" }}><span style={{ color:"#b8bcda" }}>{label}</span><span style={{ color:"#7a84a8" }}>{parts}</span></div>; })}</>)}
</Section>
)}
{hasMeals && (
<Section title="Meals" icon="🥗" accent="#4ecba0">
{Object.entries(MEAL_LABELS).map(([key,{label,icon}])=>entry.meals[key].trim()?<div key={key} style={{ marginBottom:12 }}><div style={{ fontSize:10, color:"#7a84a8", textTransform:"uppercase", letterSpacing:"0.1em", marginBottom:4, fontFamily:"'Syne Mono', monospace" }}>{icon} {label}</div><div style={{ fontSize:13, color:"#c0c8e0", fontFamily:"'Syne Mono', monospace" }}>{entry.meals[key]}</div></div>:null)}
</Section>
)}
{entry.notes&&entry.notes.trim()&&<Section title="Notes" icon="📝" accent="#a67cfc"><div style={{ fontSize:13, color:"#c0c8e0", fontFamily:"'Syne Mono', monospace", lineHeight:1.6, fontStyle:"italic" }}>{entry.notes}</div></Section>}
<div style={{ display:"flex", gap:10, marginTop:8 }}>
<button onClick={onEdit} style={{ flex:1, background:"#141824", border:"1px solid #4f7fe844", borderRadius:10, padding:"12px", color:"#4f7fe8", fontSize:12, fontWeight:600, cursor:"pointer", fontFamily:"'Syne Mono', monospace" }}>✏️ Edit Entry</button>
<button onClick={onDelete} style={{ flex:1, background:"#1a1020", border:"1px solid #e05c7a44", borderRadius:10, padding:"12px", color:"#e05c7a", fontSize:12, fontWeight:600, cursor:"pointer", fontFamily:"'Syne Mono', monospace" }}>🗑️ Delete Entry</button>
</div>
</div>
);
};

export default function App() {
const [log, setLog] = useState(deepClone(EMPTY_LOG));
const [saved, setSaved] = useState(false);
const [copied, setCopied] = useState(false);
const [history, setHistory] = useState([]);
const [view, setView] = useState("log");
const [selectedEntry, setSelectedEntry] = useState(null);
const [toast, setToast] = useState(null);
const [loading, setLoading] = useState(true);

useEffect(() => {
loadHistory();
}, []);

const loadHistory = async () => {
const { data, error } = await supabase
.from("health_logs")
.select("*")
.order("date", { ascending: false });
if (!error && data) setHistory(data.map(row => ({ ...row, vitals: row.vitals||EMPTY_LOG.vitals, workouts: row.workouts||EMPTY_LOG.workouts, meals: row.meals||EMPTY_LOG.meals })));
setLoading(false);
};

const showToast = (msg, color="#4ecba0") => {
setToast({ msg, color });
setTimeout(() => setToast(null), 2500);
};

const updateVitals = (time, field, val) => setLog(l=>({...l, vitals:{...l.vitals,[time]:{...l.vitals[time],[field]:val}}}));
const updateHome = (field, val) => setLog(l=>({...l, workouts:{...l.workouts, home:{...l.workouts.home,[field]:val}}}));
const updateGym = (field, val) => setLog(l=>({...l, workouts:{...l.workouts, gym:{...l.workouts.gym,[field]:val}}}));
const updateMachine = (machine, field, val) => setLog(l=>({...l, workouts:{...l.workouts, machines:{...l.workouts.machines,[machine]:{...l.workouts.machines[machine],[field]:val}}}}));
const updateMeal = (field, val) => setLog(l=>({...l, meals:{...l.meals,[field]:val}}));

const saveLog = async () => {
const entry = { ...deepClone(log), id: log.id || Date.now().toString() };
const { error } = await supabase.from("health_logs").upsert(entry);
if (error) { showToast("⚠️ Save failed — try again", "#e05c7a"); return; }
await loadHistory();
setSaved(true);
showToast("✓ Entry saved!", "#4ecba0");
setTimeout(() => setSaved(false), 2200);
};

const shareWithCoach = async () => {
const summary = generateCoachSummary(log);
try {
await navigator.clipboard.writeText(summary);
setCopied(true);
showToast("📋 Copied! Paste it to your coach.", "#f0c060");
setTimeout(() => setCopied(false), 3000);
} catch { showToast("⚠️ Copy failed — try again", "#e05c7a"); }
};

const newDay = () => setLog({ ...deepClone(EMPTY_LOG), date: todayStr() });

const handleEditEntry = (entry) => { setLog(deepClone(entry)); setView("log"); setSelectedEntry(null); };

const handleDeleteEntry = async (entry) => {
await supabase.from("health_logs").delete().eq("id", entry.id);
await loadHistory();
setSelectedEntry(null);
setView("history");
showToast("🗑️ Entry deleted", "#e05c7a");
};

return (
<>
<style>{`
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@600;700&family=Syne+Mono&display=swap');
* { box-sizing:border-box; margin:0; padding:0; }
body { background:#0c0f1a; }
::-webkit-scrollbar { width:4px; }
::-webkit-scrollbar-track { background:#0c0f1a; }
::-webkit-scrollbar-thumb { background:#252c42; border-radius:3px; }
input::placeholder, textarea::placeholder { color:#2e3550; }
@keyframes fadeIn { from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)} }
@keyframes toastIn { from{opacity:0;transform:translateX(20px)}to{opacity:1;transform:translateX(0)} }
.log-section{animation:fadeIn 0.35s ease both}
.btn-coach{background:linear-gradient(135deg,#c8922a 0%,#f0c060 100%);border:none;border-radius:10px;color:#1a1200;padding:11px 22px;font-size:12px;cursor:pointer;letter-spacing:0.08em;font-family:'Syne Mono',monospace;font-weight:600;transition:all 0.2s;box-shadow:0 4px 18px rgba(240,192,96,0.35);display:flex;align-items:center;gap:7px}
.btn-coach:hover{transform:translateY(-1px)}
.btn-save{background:linear-gradient(135deg,#2a4bc8 0%,#4f7fe8 100%);border:none;border-radius:10px;color:#fff;padding:11px 26px;font-size:12px;cursor:pointer;letter-spacing:0.08em;font-family:'Syne Mono',monospace;font-weight:600;transition:all 0.2s;box-shadow:0 4px 18px rgba(79,127,232,0.35)}
.btn-ghost{background:transparent;border:1px solid #252c42;border-radius:10px;color:#7a84a8;padding:11px 18px;font-size:11px;cursor:pointer;letter-spacing:0.08em;font-family:'Syne Mono',monospace;transition:all 0.15s}
.btn-ghost:hover{border-color:#3a4462;color:#a0aac8}
.history-card{transition:border-color 0.15s,background 0.15s}
.history-card:hover{border-color:#3a4462!important;background:#161c2e!important;cursor:pointer}
`}</style>

{toast && <div style={{ position:"fixed", top:20, right:20, zIndex:9999, background:"#1a1f30", border:`1px solid ${toast.color}55`, borderRadius:10, padding:"12px 18px", color:toast.color, fontSize:12, fontFamily:"'Syne Mono', monospace", boxShadow:"0 8px 32px rgba(0,0,0,0.4)", animation:"toastIn 0.25s ease both" }}>{toast.msg}</div>}

<div style={{ minHeight:"100vh", background:"#0c0f1a", color:"#dde0f0", fontFamily:"'Syne Mono', monospace", paddingBottom:80 }}>
<div style={{ background:"linear-gradient(180deg,#111422 0%,#0c0f1a 100%)", borderBottom:"1px solid #1a1f30", padding:"20px 24px 16px", position:"sticky", top:0, zIndex:100 }}>
<div style={{ maxWidth:700, margin:"0 auto", display:"flex", justifyContent:"space-between", alignItems:"center", flexWrap:"wrap", gap:12 }}>
<div>
<div style={{ fontSize:9, letterSpacing:"0.25em", color:"#4f7fe8", textTransform:"uppercase", marginBottom:4 }}>Health &amp; Wellness · v3.0</div>
<div style={{ fontFamily:"'Syne', sans-serif", fontSize:20, fontWeight:700, color:"#e8eaf8" }}>Tim's Wellness Log</div>
</div>
<button className="btn-ghost" onClick={()=>{ setView(view==="log"?"history":"log"); setSelectedEntry(null); }}>
{view==="log" ? `📋 History (${history.length})` : "✏️ Today"}
</button>
</div>
</div>

<div style={{ maxWidth:700, margin:"0 auto", padding:"24px 16px 0" }}>
{view==="log" && (
<>
{log.id && <div style={{ background:"#0f1320", border:"1px solid #4f7fe822", borderRadius:10, padding:"10px 16px", marginBottom:18, fontSize:11, color:"#4f7fe8", fontFamily:"'Syne Mono', monospace" }}>✏️ Editing entry for {formatDate(log.date)}<button onClick={newDay} style={{ float:"right", background:"none", border:"none", color:"#4a5270", cursor:"pointer", fontSize:11, fontFamily:"'Syne Mono', monospace" }}>✕ New Entry</button></div>}

<div className="log-section" style={{ display:"flex", gap:14, marginBottom:22, flexWrap:"wrap" }}>
<div style={{ flex:"1 1 200px" }}>
<Field label="Date" value={log.date} onChange={v=>setLog(l=>({...l,date:v}))} />
<div style={{ fontSize:10, color:"#4a5270", marginTop:5 }}>{formatDate(log.date)}</div>
</div>
<div style={{ flex:"0 0 140px" }}>
<Field label="Weight" unit="lbs" value={log.weight} onChange={v=>setLog(l=>({...l,weight:v}))} placeholder="180.2" />
<div style={{ fontSize:10, color:"#4a5270", marginTop:5 }}>Morning · Unclothed</div>
</div>
</div>

<div className="log-section">
<Section title="Vitals" icon="🩺" accent="#e05c7a">
<VitalsRow label="Morning" data={log.vitals.morning} onChange={(f,v)=>updateVitals("morning",f,v)} />
<VitalsRow label="Afternoon" data={log.vitals.afternoon} onChange={(f,v)=>updateVitals("afternoon",f,v)} />
<VitalsRow label="Evening" data={log.vitals.evening} onChange={(f,v)=>updateVitals("evening",f,v)} />
</Section>
</div>

<div className="log-section">
<Section title="Workouts" icon="💪" accent="#4f7fe8">
<Divider label="At Home — Xterra Amati" />
<div style={{ display:"flex", gap:10, flexWrap:"wrap", marginBottom:6 }}>
<Field label="Bike Set 1 · Pre-Breakfast" unit="mi" value={log.workouts.home.bike1} onChange={v=>updateHome("bike1",v)} placeholder="6" />
<Field label="Bike Set 2" unit="mi" value={log.workouts.home.bike2} onChange={v=>updateHome("bike2",v)} placeholder="2" />
<Field label="Bike Set 3" unit="mi" value={log.workouts.home.bike3} onChange={v=>updateHome("bike3",v)} placeholder="2" />
</div>
<Divider label="At the Gym" />
<div style={{ display:"flex", gap:10, flexWrap:"wrap", marginBottom:10 }}>
<Field label="Stationary Bike" unit="mi" value={log.workouts.gym.bike} onChange={v=>updateGym("bike",v)} placeholder="—" />
<Field label="Rowing Machine" unit="min" value={log.workouts.gym.rowing} onChange={v=>updateGym("rowing",v)} placeholder="—" />
</div>
<Divider label="Precor Machines" />
{Object.entries(MACHINE_LABELS).map(([key,label])=>(
<MachineRow key={key} label={label} data={log.workouts.machines[key]} onChange={(f,v)=>updateMachine(key,f,v)} />
))}
</Section>
</div>

<div className="log-section">
<Section title="Meals" icon="🥗" accent="#4ecba0">
<div style={{ display:"flex", flexDirection:"column", gap:12 }}>
{Object.entries(MEAL_LABELS).map(([key,{label,icon}])=>(
<TextArea key={key} label={`${icon} ${label}`} value={log.meals[key]} onChange={v=>updateMeal(key,v)} placeholder="Optional" />
))}
</div>
</Section>
</div>

<div className="log-section">
<Section title="Notes & Energy" icon="📝" accent="#a67cfc">
<div style={{ marginBottom:18 }}>
<div style={{ fontSize:10, letterSpacing:"0.13em", color:"#7a84a8", textTransform:"uppercase", fontFamily:"'Syne Mono', monospace", marginBottom:8 }}>
Energy Level{log.energy?<span style={{ color:"#a67cfc", marginLeft:10 }}>{ENERGY_LABELS[log.energy]}</span>:null}
</div>
<div style={{ display:"flex", gap:8 }}>
{[1,2,3,4,5].map(n=>(
<button key={n} onClick={()=>setLog(l=>({...l,energy:l.energy===String(n)?"":String(n)}))} style={{ flex:1, padding:"10px 4px", borderRadius:8, cursor:"pointer", background:log.energy===String(n)?"#a67cfc":"#10131e", color:log.energy===String(n)?"#0c0f1a":"#4a5270", fontWeight:700, fontSize:15, border:log.energy===String(n)?"1px solid #a67cfc":"1px solid #252c42", transition:"all 0.15s" }}>{n}</button>
))}
</div>
</div>
<TextArea label="Mood · Sleep · Observations" value={log.notes} onChange={v=>setLog(l=>({...l,notes:v}))} placeholder="How are you feeling today?" />
</Section>
</div>

<div style={{ display:"flex", gap:10, justifyContent:"flex-end", alignItems:"center", marginTop:8, flexWrap:"wrap" }}>
<button className="btn-ghost" onClick={newDay}>New Day</button>
<button className="btn-coach" onClick={shareWithCoach}>{copied?"✓ Copied!":"📤 Share with Coach"}</button>
<button className="btn-save" onClick={saveLog} style={{ background:saved?"linear-gradient(135deg,#1a4a30 0%,#2a6a46 100%)":undefined }}>{saved?"✓ Saved":"Save Entry"}</button>
</div>
<div style={{ marginTop:16, padding:"12px 16px", background:"#0f1320", borderRadius:10, border:"1px solid #f0c06018", fontSize:11, color:"#7a7040", letterSpacing:"0.04em", textAlign:"center" }}>
📤 <strong style={{ color:"#c8922a" }}>Share with Coach</strong> copies your full daily summary — paste it directly into your chat with Claude.
</div>
</>
)}

{view==="history" && !selectedEntry && (
<div>
<div style={{ fontFamily:"'Syne', sans-serif", fontSize:20, fontWeight:700, marginBottom:20, color:"#c0c4e0" }}>Entry History</div>
{loading && <div style={{ textAlign:"center", color:"#4a5270", padding:40 }}>Loading...</div>}
{!loading && history.length===0 && <div style={{ textAlign:"center", color:"#4a5270", padding:60, fontSize:13 }}>No saved entries yet.<br/><span style={{ fontSize:11, color:"#343b56" }}>Save today's log to see it here.</span></div>}
{history.map((entry,i)=>(
<div key={entry.id||i} className="history-card" onClick={()=>{ setSelectedEntry(entry); setView("detail"); }}
style={{ background:"#141824", border:"1px solid #1e2438", borderRadius:14, padding:"16px 20px", marginBottom:14, animation:"fadeIn 0.3s ease both" }}>
<div style={{ display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:10, flexWrap:"wrap", gap:8 }}>
<div>
<div style={{ fontFamily:"'Syne', sans-serif", fontWeight:700, fontSize:15, color:"#dde0f0" }}>{formatDate(entry.date)}</div>
{entry.energy&&<div style={{ fontSize:11, color:"#a67cfc", marginTop:3, fontFamily:"'Syne Mono', monospace" }}>⚡ {ENERGY_LABELS[entry.energy]}</div>}
</div>
<div style={{ display:"flex", alignItems:"center", gap:12 }}>
{entry.weight&&<div style={{ fontSize:22, fontFamily:"'Syne', sans-serif", fontWeight:700, color:"#4f7fe8" }}>{entry.weight} <span style={{ fontSize:11, color:"#4a5270", fontWeight:400 }}>lbs</span></div>}
<span style={{ color:"#3a4462", fontSize:20 }}>›</span>
</div>
</div>
<div style={{ display:"flex", gap:14, flexWrap:"wrap", fontSize:11, color:"#7a84a8" }}>
{entry.vitals?.morning?.sys&&<span>🩺 AM {entry.vitals.morning.sys}/{entry.vitals.morning.dia} · {entry.vitals.morning.hr} bpm</span>}
{entry.vitals?.afternoon?.sys&&<span>🩺 PM {entry.vitals.afternoon.sys}/{entry.vitals.afternoon.dia}</span>}
{entry.vitals?.evening?.sys&&<span>🩺 Eve {entry.vitals.evening.sys}/{entry.vitals.evening.dia}</span>}
{entry.workouts?.home?.bike1&&<span>🚴 {[entry.workouts.home.bike1,entry.workouts.home.bike2,entry.workouts.home.bike3].filter(Boolean).join("+")} mi home</span>}
{entry.workouts?.gym?.bike&&<span>🏋️ {entry.workouts.gym.bike} mi gym</span>}
{entry.workouts?.gym?.rowing&&<span>🚣 {entry.workouts.gym.rowing} min row</span>}
</div>
{entry.notes&&<div style={{ marginTop:10, fontSize:11, color:"#5d667f", fontStyle:"italic", borderTop:"1px solid #1a1f30", paddingTop:10 }}>{entry.notes.slice(0,80)}{entry.notes.length>80?"…":""}</div>}
</div>
))}
</div>
)}

{view==="detail" && selectedEntry && (
<HistoryDetail
entry={selectedEntry}
onBack={()=>{ setView("history"); setSelectedEntry(null); }}
onEdit={()=>handleEditEntry(selectedEntry)}
onDelete={()=>handleDeleteEntry(selectedEntry)}
/>
)}
</div>
</div>
</>
);
}
